project:
  type: book
  output-dir: build

book:
  title: "MusAI Learning Resources"
  subtitle: "Building Critical Interdisciplinary Studies"
  navbar:
    background: "white"
    foreground: "#dd5c00" 
    search: true
    title: "MusAI Learning Resources"
    pinned: true
  chapters:
    - index.qmd 
    # - part: research.qmd
    #   chapters:       
    #   - research/survey.qmd
    # - part: playground.qmd
    #   chapters:
    #   - playground/notebook.qmd
    #   - playground/references.qmd
    - part: sessions.qmd
      chapters:
        - sessions/1_culture.qmd
        - sessions/2_models.qmd
        - sessions/3_politicaleconomy1.qmd
        - sessions/4_politicaleconomy2.qmd
        - sessions/5_personalisation.qmd
        - sessions/6_copyright.qmd
        - sessions/7_others.qmd
        - sessions/8_creativepractice1.qmd
        - sessions/9_creativepractice2.qmd
        - sessions/10_artcritique.qmd
    - references.qmd



# this would be a global bib, but I think we can have them per-page too
bibliography: playground/references.bib

format:
  html:
    number-sections: true
    number-depth: 0
    theme:
      - litera
      - theme-light.scss 
      - brand
    template-partials: 
      - title-block.html
    title-block-banner: "rbg(0,0,0,0)"
    # title-block-banner: images/resources/images/xenia-mallet-ag2.webp
    title-block-banner-color: "#dd5c00"
    title-block-style: default
    include-in-header:
      - text: |
          <style>


          .duotone:before, .duotone:after{
            content: '';
            width:100%;
            height:100%;
            position: absolute;
            top:0;
            left: 0;
          }

          .duotone:before{              
              background-color: #000097;
              mix-blend-mode: lighten;
          }

          .duotone:after {            
            background-color: #dd5c00;
            mix-blend-mode: overlay;
          }

          .quarto-title-banner {            
            height:200px;           
            position:relative;
            background-image: url(/resources/images/xenia-mallet-ag2-grayscale.png) ;
            background-repeat: no-repeat;
            background-position-y: 12%;
            background-size: cover;
          }
          
          .overlay {
            height:200px;
            background-color:rgb(255,255,255,0.8);
            mix-blend-mode: normal;
          }

          .quarto-title-banner h1 {            
              color: #dd5c00f;
              
              z-index:1;                 
              # mix-blend-mode: overlay;                 
            }

          .sidebar-item-container > a >  span {
            font-variant-caps: small-caps;
          }

          </style>  

website: 
  page-footer: |
    <img src="/resources/images/logo_erc-flag_fp-edited.png" width="200" /> 
    <img src="/resources/images/2560px-university_college_london_logo.svg_-2.webp" width="200" />
    <br/>
    <a href="https://musairesearch.github.io/LearningResources/">MusAI Learning Resources</a> © 2026 by <a href="https://musicairesearch.wordpress.com/">MusAI</a> is licensed under
    <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">
    <img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">
    <img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">

  


